version: '3.7'
# https://docs.docker.com/compose/compose-file/

x-sso-variables: &sso-variables
  SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
  EXTERNAL_SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
  EXTERNAL_ENC_SECRET_KEY: JWTEncKeyDontUseInProduction666!
  sso.jwt.internal.signature.key.type: ENV
  sso.jwt.internal.signature.key.value: SIG_SECRET_KEY

x-actuator-variables: &actuator-variables
  management.endpoints.web.exposure.include: "*"
  management.endpoints.enabled-by-default: "true"

x-eureka-variables: &eureka-variables
  eureka.client.service-url.defaultZone: http://registry:8080/eureka

x-activemq-variables: &activemq-variables
  spring.activemq.broker-url: tcp://message-broker:61616
  spring.activemq.user: admin
  spring.activemq.password: admin

x-database-variables: &database-variables
  spring.liquibase.enabled: 'true'
  spring.datasource.username: root
  spring.datasource.password: root
  spring.datasource.driver-class-name: com.mysql.jdbc.Driver
  spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

x-space-variables: &space-variables
  space-controller.enabled: 'true'
  space-controller.datasource.strategy: SWITCH_DATASOURCE
  space-controller.space-filter.should-not-filter-paths[0]: /actuator/**
  space-controller.spaces[0].id: draft
  space-controller.spaces[1].id: final
  space-controller.spaces[0].datasource.driver-class-name: com.mysql.jdbc.Driver
  space-controller.spaces[0].datasource.type: com.zaxxer.hikari.HikariDataSource
  space-controller.spaces[0].datasource.username: root
  space-controller.spaces[0].datasource.password: root
  space-controller.spaces[1].datasource.driver-class-name: com.mysql.jdbc.Driver
  space-controller.spaces[1].datasource.type: com.zaxxer.hikari.HikariDataSource
  space-controller.spaces[1].datasource.username: root
  space-controller.spaces[1].datasource.password: root

services:
  message-broker:
    image: rmohr/activemq:5.15.9-alpine
    container_name: demo_activemq
    privileged: true
    ports:
      - "61616:61616"
      - "8161:8161"
      - "5672:5672"
      - "61613:61613"
      - "1883:1883"
      - "61614:61614"

  mysql:
    image: mysql:5.7.18
    # Set max_allowed_packet to 512M for provisioning
    command: --max-allowed-packet=512M --performance-schema=FALSE --transaction-isolation=READ-COMMITTED --init-connect='SET collation_connection=utf8_bin' --init-connect='SET NAMES utf8;' --character-set-server=utf8 --collation-server=utf8_bin --lower-case-table-names=2 --max-connections=500
    container_name: demo_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - demo_mysql_data:/var/lib/mysql

  registry:
    image: repo.backbase.com/backbase-docker-releases/registry:IPS-1.12.0
    ports:
      - "8761:8080"
    environment:
      <<: *sso-variables

  token-converter:
    image: repo.backbase.com/backbase-docker-releases/bb-authentication-token-converter-service:IPS-1.12.0
    ports:
      - "7779:8080"
    environment:
      <<: *sso-variables
      <<: *eureka-variables
      backbase.events.enabled: 'false'
      backbase.activemq.enabled: 'false'
    links:
      - registry

  edge:
    image: repo.backbase.com/backbase-docker-releases/edge:IPS-1.12.0
    ports:
      - "8754:8080"
    environment:
      <<: *eureka-variables
      gateway.actuator.user: admin
      gateway.actuator.password: admin
    links:
      - registry
      - token-converter

  auth:
    image: repo.backbase.com/backbase-docker-releases/authentication-dev:IPS-1.12.0-no-production
    ports:
      - "7777:8080"
    environment:
      <<: *sso-variables
      <<: *eureka-variables
      <<: *activemq-variables
    links:
      - registry
      - message-broker

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8764:8080"
      - "8774:8090"
    links:
      - edge

  space-controller:
    image: repo.backbase.com/backbase-docker-releases/space-controller:CXS-6.2.5
    hostname: space-controller
    ports:
      - "8080:8080"
    environment:
      <<: *sso-variables
      <<: *actuator-variables
      <<: *eureka-variables
      <<: *activemq-variables
      <<: *database-variables
      spring.datasource.url: jdbc:mysql://mysql:3306/space_controller?useSSL=false&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      space-controller.transitions.four-eyes-enabled: 'false'
    links:
      - message-broker
      - registry
      - mysql

  contentservices:
    image: repo.backbase.com/backbase-docker-releases/contentservices:CXS-6.2.5
    hostname: contentservices
    ports:
      - "8040:8080"
    environment:
      <<: *sso-variables
      <<: *actuator-variables
      <<: *eureka-variables
      <<: *activemq-variables
      <<: *database-variables
      <<: *space-variables
      contentservices.extension-points.enabled: 'true'
      contentservices.provisioning.enabled: 'true'
      spring.datasource.url: jdbc:mysql://mysql:3306/cs_final?useSSL=false&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      space-controller.spaces[0].datasource.url: jdbc:mysql://mysql:3306/cs_draft?useSSL=false&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      space-controller.spaces[1].datasource.url: jdbc:mysql://mysql:3306/cs_final?useSSL=false&cacheServerConfiguration=true&createDatabaseIfNotExist=true
    links:
      - mysql
      - registry
      - message-broker

  portal:
    image: repo.backbase.com/backbase-docker-releases/portal:CXS-6.2.5
    hostname: portal
    ports:
      - "8070:8080"
    environment:
      <<: *sso-variables
      <<: *actuator-variables
      <<: *eureka-variables
      <<: *activemq-variables
      <<: *database-variables
      <<: *space-variables
      portal.resourcelocation.profile: filesystem
      portal.resourcelocation.path: /home/nonroot/portal/home/fs_contextroot
      portal.extension-points.enabled: 'true'
      portal.content.enabled: 'true'
      spring.jpa.properties.hibernate.session_factory_name_is_jndi: 'false'
      spring.datasource.url: jdbc:mysql://mysql:3306/portal_final?useSSL=false&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      space-controller.spaces[0].datasource.url: jdbc:mysql://mysql:3306/portal_draft?useSSL=false&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      space-controller.spaces[1].datasource.url: jdbc:mysql://mysql:3306/portal_final?useSSL=false&cacheServerConfiguration=true&createDatabaseIfNotExist=true
    links:
      - mysql
      - registry
      - contentservices
      - message-broker

  provisioning:
    image: repo.backbase.com/backbase-docker-releases/provisioning:CXS-6.2.5
    hostname: provisioning
    ports:
      - "8090:8080"
    environment:
      <<: *sso-variables
      <<: *actuator-variables
      <<: *eureka-variables
      <<: *activemq-variables
      <<: *database-variables
      spring.datasource.url: jdbc:mysql://mysql:3306/provisioning?useSSL=false&cacheServerConfiguration=true&createDatabaseIfNotExist=true
    links:
      - mysql
      - registry
      - message-broker

  statics:
    image: docker.io/torrespro/import-statics:latest
    volumes:
      - ./job.yaml:/import/job.yaml
    links:
      - edge
      - portal
      - contentservices
      - provisioning
    command: sh -c "dockerize -wait http://edge:8080/api/provisioning/actuator/health/liveness -timeout 300s -wait-retry-interval 30s ./import-statics.py"

volumes:
  demo_mysql_data: